stages:
  - test
  - build


cache:
  paths:
    - .cache/pip
    - venv/


test:spp-api:
  stage: test
  image: python:3.10-slim
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "staging" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      changes:
        - "**/*.py"
      when: always
  before_script:
  - |
    python -m venv venv
    source venv/bin/activate
    pip install --cache-dir .cache/pip .[test]
  script:
    - pytest -W ignore


build:
  rules:
    - if: $CI_COMMIT_BRANCH == "staging"
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - | # ssh connection setup
      chmod og= $CI_DEPLOY_USER_SSH_PRIVATE_KEY
      apk update
      apk add openssh-client
    - | # build and push api image to gitlab registry
      docker login --username gitlab-ci-token --password $CI_JOB_TOKEN $CI_REGISTRY
      docker build --rm --tag ${CI_REGISTRY_IMAGE}/api:${CI_API_IMAGE_TAG} --file ./Dockerfile .
      docker push ${CI_REGISTRY_IMAGE}/api:${CI_API_IMAGE_TAG}
