version: "3.8"

services:
  redis:
    image: redis:7.2.4
    restart: always
    command: redis-server --save 20 1 --loglevel debug --requirepass $REDIS_PASSWORD
    healthcheck:
        test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
        interval: 4s
        timeout: 10s
        retries: 5
    volumes:
      - redis:/data

  api:
    image: albert/spp/api:latest # Build image with the Dockerfile before running this docker-compose.yml
    ports:
      - 8000:8000
    restart: always
    command: uvicorn api.app:app --proxy-headers --root-path ${API_ROOT_PATH} --forwarded-allow-ips='*' --host 0.0.0.0 --port 8000 --log-level debug
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=mypassword
      - ENV=dev
      - APP_VERSION=1.0.0
      - "LLM_TABLE=[('AgentPublic/fabrique-reference-2', 'http://localhost:8080')]" # Warning: LLM model must be started before the API server
      - API_KEYS_FILE=/code/keys/api_keys.json
    volumes:
      - ./keys:/code/keys
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis: