version: "3.8"

services:
  redis:
    image: redis:7.2.4
    restart: always
    healthcheck:
        test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
        interval: 4s
        timeout: 10s
        retries: 5
    volumes:
      - redis:/data

  api:
    image: albert-spp/api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: always
    command: uvicorn api.app:app --proxy-headers --forwarded-allow-ips='*' --host 0.0.0.0 --port 8000 --log-level debug
    environment:
      - API_KEYS=changeme
      - ENV=dev
      - APP_VERSION=1.0.0
      - ALBERT_BASE_URL=http://localhost:8080/v1
      - ALBERT_API_KEY=changeme
      - LANGUAGE_MODEL=AgentPublic/llama3-fabrique-texte
      - EMBEDDINGS_MODEL=AgentPublic/llama3-fabrique-texte
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis: