version: "3.8"

services:
  api:
    image: ${CI_REGISTRY_IMAGE}/api:${CI_API_IMAGE_TAG}
    container_name: ${COMPOSE_PROJECT_NAME}-${API_PORT}-api
    ports:
      - ${API_PORT}:8000
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - ENV=${ENV:-dev}
      - "LLM_TABLE=${LLM_TABLE}"
    depends_on:
      redis:
        condition: service_healthy
  redis:
    image: redis:7.2.4
    container_name: ${COMPOSE_PROJECT_NAME}-${API_PORT}-redis
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    healthcheck:
        test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
        interval: 4s
        timeout: 10s
        retries: 5