version: "3.8"

services:
  redis:
    image: redis:7.2.4
    restart: always
    command: redis-server --save 20 1 --loglevel debug --requirepass mtppassword
    healthcheck:
        test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
        interval: 4s
        timeout: 10s
        retries: 5
    volumes:
      - redis:/data

  api:
    image: albert-spp/api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: always
    command: uvicorn api.app:app --proxy-headers --forwarded-allow-ips='*' --host 0.0.0.0 --port 8000 --log-level debug
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=mypassword
      - ENV=dev
      - APP_VERSION=1.0.0
      - MODEL_NAME=AgentPublic/llama3-fabrique-texte
      - MODELS_URLS=["https://localhost:8001"]
      - API_KEYS_FILE=/code/keys/api_keys.example.json
    volumes:
      - .:/code/keys
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis: